"""Private Asset v1 contracts and ingestion boundary."""

from .access import (
    ASSET_ACCESS_SCHEMA_VERSION,
    AssetAccessContractError,
    AssetAccessError,
    AssetAccessPolicy,
    AssetAccessUnavailableError,
    AssetNotReadyError,
    PrivateObjectAccessSigner,
    SignedAssetReadAccess,
    issue_asset_read_access,
)
from .generated import GENERATED_ASSET_NAMESPACE, generated_asset_id
from .ingestion import (
    AssetConflictError,
    AssetContentRejectedError,
    AssetIngestionError,
    AssetLineageError,
    AssetMetadataRepository,
    adopt_stored_asset,
    build_object_key,
    content_metadata,
    detect_content_type,
    finalize_staged_asset,
    ingest_asset,
    stage_asset_object,
    validate_asset_object_key,
)
from .models import (
    ASSET_SCHEMA_VERSION,
    Asset,
    AssetContentType,
    AssetErrorCode,
    AssetIngestionPolicy,
    AssetIngestionRequest,
    AssetKind,
    AssetStatus,
    PrivateObjectMetadata,
    StoredObject,
)
from .storage import (
    AssetStorageConflictError,
    AssetStorageError,
    PrivateObjectMaintenance,
    PrivateObjectMetadataReader,
    PrivateObjectStore,
    PrivateObjectVersionDeleter,
)

__all__ = [
    "ASSET_ACCESS_SCHEMA_VERSION",
    "ASSET_SCHEMA_VERSION",
    "Asset",
    "AssetAccessContractError",
    "AssetAccessError",
    "AssetAccessPolicy",
    "AssetAccessUnavailableError",
    "AssetConflictError",
    "AssetContentRejectedError",
    "AssetContentType",
    "AssetErrorCode",
    "AssetIngestionError",
    "AssetIngestionPolicy",
    "AssetIngestionRequest",
    "AssetKind",
    "AssetLineageError",
    "AssetMetadataRepository",
    "AssetNotReadyError",
    "AssetStatus",
    "AssetStorageConflictError",
    "AssetStorageError",
    "GENERATED_ASSET_NAMESPACE",
    "PrivateObjectMaintenance",
    "PrivateObjectMetadata",
    "PrivateObjectMetadataReader",
    "PrivateObjectStore",
    "PrivateObjectVersionDeleter",
    "PrivateObjectAccessSigner",
    "SignedAssetReadAccess",
    "StoredObject",
    "adopt_stored_asset",
    "build_object_key",
    "content_metadata",
    "detect_content_type",
    "finalize_staged_asset",
    "generated_asset_id",
    "ingest_asset",
    "issue_asset_read_access",
    "stage_asset_object",
    "validate_asset_object_key",
]
