"""Jewelry design contracts. Import concrete types from jewelai_domain.models."""

from .dictionary import (
    DICTIONARY_SCHEMA_VERSION,
    AmbiguousMatch,
    DictionaryCategory,
    DictionaryRegistry,
    ResolvedMatch,
    UnsupportedMatch,
    load_domain_dictionary,
)
from .models import SCHEMA_VERSION, Design, DesignRevision
from .questions import (
    QUESTION_SCHEMA_VERSION,
    QuestionCatalog,
    QuestionId,
    RenderedQuestion,
    SchemaTarget,
    UnknownQuestionError,
    load_question_catalog,
)
from .revisions import RevisionConflict, confirm_field, lock_field, revise_design, unlock_field
from .roles import (
    ROLE_SCHEMA_VERSION,
    RoleId,
    RoleProfile,
    RoleRegistry,
    UnknownRoleError,
    UnsupportedLocaleError,
    load_role_profiles,
)
from .rules import (
    RULES_SCHEMA_VERSION,
    AskDecision,
    AssumeDecision,
    AvailableKnowledgeFact,
    BlockDecision,
    DeriveDecision,
    Gap,
    GapState,
    ProposedDomainUpdate,
    ReadyDecision,
    RuleRegistry,
    analyze_gaps,
    load_rules,
)

__all__ = [
    "DICTIONARY_SCHEMA_VERSION",
    "QUESTION_SCHEMA_VERSION",
    "RULES_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "AmbiguousMatch",
    "AskDecision",
    "AssumeDecision",
    "AvailableKnowledgeFact",
    "BlockDecision",
    "Design",
    "DesignRevision",
    "DictionaryCategory",
    "DictionaryRegistry",
    "DeriveDecision",
    "Gap",
    "GapState",
    "ProposedDomainUpdate",
    "QuestionCatalog",
    "QuestionId",
    "RevisionConflict",
    "ResolvedMatch",
    "RenderedQuestion",
    "ReadyDecision",
    "ROLE_SCHEMA_VERSION",
    "RoleId",
    "RoleProfile",
    "RoleRegistry",
    "RuleRegistry",
    "SchemaTarget",
    "UnknownQuestionError",
    "UnknownRoleError",
    "UnsupportedLocaleError",
    "UnsupportedMatch",
    "confirm_field",
    "analyze_gaps",
    "lock_field",
    "load_domain_dictionary",
    "load_question_catalog",
    "load_rules",
    "load_role_profiles",
    "revise_design",
    "unlock_field",
]
